[package]
name = "clan"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }
Fanship = { local = "../fanship" }

[addresses]
clan = "0x0"
fanship = "0x0"